### ISSUE TITLE
extension conflict error

### ISSUE THREAD

**Issue by OneNewLife** [FelisCatus/SwitchyOmega#1012]
os: Fedora
kernal: 4.9.12
issue: The proxy settings are controlled by other app(s) or extension(s). Please disable or uninstall the apps or extensions in conflict.
decripttion: this morning i updated NetworkManager and then the SwitchyOmega show this error

SwitchyOmega 2.4.1
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by FelisCatus** [comment]
Unfortunately, there is nothing I can do from my side, since Chrome decides whether SwitchyOmega could control the proxy settings.

This is mostly related to other extensions that you have installed in Chrome. Please try removing SwitchyOmega and reinstall it from Chrome Web Store. That could increase its priority and probably solve the problem.

**Comment by uRusure** [comment]
@FelisCatus wow! Finally, I fixed this issue with your advice! I've been suffering from this so long. xD Because I had SwitchyOmega and NordVPN installed before and was using them together without any conflicts but then something happened and that error popped up...
