### ISSUE TITLE
Rules with https://*.example.com/* is not working

### ISSUE THREAD

**Issue by PekaFat** [FelisCatus/SwitchyOmega#1015]
Hi, when I set rule like this:
![image](https://cloud.githubusercontent.com/assets/13280748/23592004/b96f64ec-0213-11e7-80c2-40199133ead7.png)

It's does not work even with http, proxy does not activates, but this:
![image](https://cloud.githubusercontent.com/assets/13280748/23592026/0de6a594-0214-11e7-87cd-6cab76405650.png)
Is working fine. Can it be fixed or it's Chrome (56.0.2924.87) issue?

**Comment by celeron533** [comment]
For the security reasons, chrome doesn't allow wildcard in https URL

**Comment by PekaFat** [comment]
> For the security reasons, chrome doesn't allow wildcard in https URL

But this does not work even with http.

**Comment by FelisCatus** [comment]
This is probably because your website URL is `https://rutracker.org/something`, which does not contain a dot before `rutracker`. In that case, `https://*.` can't match anything.

Such cases are better handled with Host wildcard conditions, where you can just put `*.rutracker.org` and forget about it. In that case, SwitchyOmega handles `*.` specially and treat it as `rutracker.org|*.rutracker.org`. Such special handling cannot be reliably done on the URL wildcard conditions though.

Or, if you want more control of the matching, regular expression might be a better choice.
