### ISSUE TITLE
Slows down page loading

### ISSUE THREAD

**Issue by maxxer** [FelisCatus/SwitchyOmega#1037]
The extension is awesome, but I noticed it slows down web browsing **a lot**, even on brand new computers. I.e. loading new content in Facebook takes up to one or two seconds

**Comment by FelisCatus** [comment]
If you see `Resolving proxy...` in the bottom left corner, this is normal because Chrome needs to compile and execute the PAC script. This only happens a few times though. After the initial compilation, the resolving will not take so long.

If you see other text shown or simply experiences network slowdown, please inspect your proxy server and your network. SwitchyOmega is a configuration tool and it does not touch network protocols. You can also use command-line flags to set the proxy without using SwitchyOmega and the result will generally be the same.

Even on perfect network, proxy servers do have a cost due to protocol overhead. Also, using proxy servers causes the DNS to be resolved remotely, voiding the speedups from DNS pre-fetch.
