### ISSUE TITLE
能请问一下你们release中的crx是怎么来的吗？

### ISSUE THREAD

**Issue by SimonTart** [FelisCatus/SwitchyOmega#1046]
I'm a chrome extension developer.I use chrome package function to build .crx file with pem for our Chinense users.It works well installed from Google Web Store.But recently our extension installed with my manual packaged .crx file is disabled by chrome.But I try your .crx file in your releases.I find it work well, so can you tell me how do you build your .crx file manually.

(Chinese Translate)
我也是一个chrome extension的开发者，我平时都是在开发模式下通过pem打包出来给国内的用户。但是最近安装会被chrome禁用。用了一下你们的发现你们的可以，能请问一下你们的crx是怎么打包出来的吗？

**Comment by FelisCatus** [comment]
The CRX packages on the releases page are downloaded from Chrome Web Store. In the developer dashboard, when an uploaded version has been reviewed and published, there will be a link to download CRX. Such CRX files are generally trusted by Chrome since it has signatures from the Chrome Web Store. We never build CRX ourselves.

Please note that some users still report issues where Chrome disables the extension. I have no idea why though.

P.S. I'm available in both English and Chinese. Feel free to ask in either language.

这个项目的 Release 页面的所有 CRX 包都是从 Chrome Web Store 下载的。在开发者面板上，对于所有上传并且审核通过的版本，都会有一个下载  CRX 的链接。这样下载的 CRX 文件一般会被 Chrome 信任，因为其含有 Chrome Web Store 的签名。我们从不自己打 CRX 包。

请注意有些用户仍然反馈 Chrome 会禁用扩展。我不知道原因是什么。

注：用英文或者中文问都可以，我这边都能回答。
