### ISSUE TITLE
Proxy SwitchyOmega не  дает зайти через прокси

### ISSUE THREAD

**Issue by Riska89** [FelisCatus/SwitchyOmega#1108]
http://prntscr.com/fn9pnz
4 дня назад все работало

**Comment by EMLVIRUS** [comment]
@Riska89 This image seems requiring username& password to access. You can directly press `Ctrl + V` to posting images on GitHub

**Comment by Riska89** [comment]
![screenshot_3](https://user-images.githubusercontent.com/29654854/27485548-d257704e-5835-11e7-8562-7b472c2010da.jpg)

**Comment by celeron533** [comment]
Before I could understand Russian, the dialog box in the screenshot may caused by proxy server authentication (you are allowed to use the proxy) or the target website authentication (you are allow to view some webpages)

By using online OCR and translation tool, here is the result

```
Authorization required
To access the proxy server http//185.80.149.42:4040
You must specify a username and password.
Connection Web site is not protected
Password:
Enter 'Cancel'
```

@Riska89 , it seems your proxy server requires username and password.
You could set up it in the Options page.
In Chrome, only http and https proxy protocols support authentication.

![image](https://user-images.githubusercontent.com/3608762/27488703-8be0b820-586a-11e7-8c98-ea8278a3f0bc.png)

![image](https://user-images.githubusercontent.com/3608762/27488719-9bd959b2-586a-11e7-9035-8e2095601191.png)
