### ISSUE TITLE
Enable background running

### ISSUE THREAD

**Issue by unrated1** [FelisCatus/SwitchyOmega#1117]
Can u add SwitchyOmega to background context menu? All the powerful extension are in this menu:
![asdf](https://user-images.githubusercontent.com/13558344/28047776-c62ea844-6601-11e7-8671-c8b57c039576.png)

and i need at last 1 extension in this menu for working my browser background well.

**Comment by celeron533** [comment]
For what reason and why?

**Comment by unrated1** [comment]
Because chrome background option, this option:
![asd](https://user-images.githubusercontent.com/13558344/28069128-883aa4be-665d-11e7-9c32-d6bb352307af.png)

Not working if at last have 1 extension in this menu
And if this option work chrome browsere can very fast open and it's better for your users.
Thank you

**Comment by FelisCatus** [comment]
I have no idea on how to add items to the tray icon context menu. Also, background running is for apps, not extensions. SwitchyOmega is an extension and therefore can't do that.

**Comment by unrated1** [comment]
No against his name it's exactly for extension not app
This 3 goddess vpn (with your family group) have tray context menu
Maybe you figure out with reverse engineer?
https://chrome.google.com/webstore/detail/zenmate-vpn-best-cyber-se/fdcgdnkidjaadafnichfpabhfomcebme?utm_source=chrome-ntp-icon

https://chrome.google.com/webstore/detail/dotvpn-%E2%80%94-a-better-way-to/kpiecbcckbofpmkkkdibbllpinceiihk/related?utm_source=chrome-ntp-icon

https://chrome.google.com/webstore/detail/browsec-vpn-free-and-unli/omghfjlpggmjjaagoclmmobgdodcjboh?utm_source=chrome-ntp-icon

Also this is a simple extension, maybe u can figure out with this?

https://chrome.google.com/webstore/detail/block-peyvandhair/iohmejjebcbeokbdmcpoboepfakmmbpp

![ert](https://user-images.githubusercontent.com/13558344/28115211-43925638-6719-11e7-9e92-549c97d28469.png)

**Comment by celeron533** [comment]
Hi @unrated1 , from your last comment, I guess you have some misunderstanding.

1. Sorry, SwitchyOmega does not belongs to any 'Family' you mentioned and has no business or trade relationships with any of them.
> This 3 goddess vpn (in your family group)

2. The 'Family' you mentioned are all VPN/Proxy service providers. All of them require authorization during the connection and these Chrome extensions also do the data relay works.
SwitchyOmega is just a tool for users to switch their **Existing** proxy servers quicker and more simple. It does not require users to register an account before use (while the 'Family' does).

3. I guess those VPN/Proxy service providers may have P2P implementations (or may not) to make their service network robust and faster with lower cost and hope all nodes (users) could always online to relay data just like Tor. That's why they set the `background` option (https://developer.chrome.com/extensions/declare_permissions#background) but consumes more memory and you will experience longer waiting time when startup Windows.
>And if this option work chrome browser can very fast open and it's better for your users.

All-in-all, I am not recommended to set SwitchyOmega in background. If you feel reopening Chrome's time is too long to wait, please do not close it after use or buy a SSD.

**Comment by unrated1** [comment]
Hi @celeron533
ok if change your mind just need change this line from manifest.json:
`"permissions": [ "proxy", "tabs", "alarms", "storage", "webRequest", "webRequestBlocking", "contextMenus", "http://*/*", "https://*/*", "ftp://*/*", "\u003Call_urls>" ],`
to this:
`"permissions": [ "proxy", "tabs", "alarms", "storage", "webRequest", "webRequestBlocking", "contextMenus", "background", "http://*/*", "https://*/*", "ftp://*/*", "\u003Call_urls>" ],`

and i change it for my own SwitchyOmega for my personal use
good luck with your freeware Companyian

**Comment by celeron533** [comment]
@unrated1 I am not the author of SwitchyOmega....
But pull requests are welcome.

**Comment by FelisCatus** [comment]
Okay, let's reopen this.

I see an issue for adding the `"background"` permission though. There is no way to enable/disable it via options. For those who don't want SwitchyOmega to run on the background, it would really be annoying to see Chrome continue running (even after its last window is closed). People usually wouldn't expect this, since the proxy configurations are for Chrome only and wouldn't make much sense after it is closed.

Any thoughts on this? And may I ask why you want SwitchyOmega to run in the background, even if you are not browsing?

**Comment by unrated1** [comment]
My problem has resolved. i add another extension (made by me) to background.
i need minimum 1 extension in background because in this case Browser process is not closed completely and i can reopen browser ten time faster any time i want.
You are right except `continue running background apps when chrome is closed` there is no any other option for every single app.

**Comment by FelisCatus** [comment]
Nice workaround by using a custom extension. I think this gives us the best of both worlds so we don't need to force anything for our users.
