### ISSUE TITLE
Possible memory issue in builds after 10-07-17

### ISSUE THREAD

**Issue by olloff** [FelisCatus/SwitchyOmega#1169]
Firefox 56.0a1 any build after 10-07-17
Windows 10 x64
SwitchyOmega 2.5.0

To reproduce, try browsing Reddit or other page with large number of links for a couple dozen of pages with extension enabled. Any profile selected (include Direct or System Proxy) will give similar result - memory heap will increase rapidly until garbage collector run. While this is not critical because of GC, it still can crash browser.
If you disable extension within this browse session, memory consumption will remains stable low [see private bytes graph](https://i.imgur.com/WeWi4mr.png).

Firefox 56.0a1 any build pre-10-07-17 (include that), are safe from this issue so it probably related to https://github.com/FelisCatus/SwitchyOmega/issues/1144 and large number of queries/log entries.
I can't tell it there is any difference between 2.5.0 and 10x build https://github.com/FelisCatus/SwitchyOmega/pull/1152#issue-248218879

**Comment by FelisCatus** [comment]
It's still too early to debug memory leaks on Firefox but I'll keep it in mind.

This is unexpected since SwitchyOmega does not operate on links or similar web content. One link-related thing that I can think of is the context menu feature in Options > Interface > Allow inspecting proxy used for page elements via context menu. Please try disabling the option, restart Firefox and try again. But if that's the case then it's 100% Firefox's fault...

The other thing may be number of requests causing the Request Monitor to gather too much information and has nothing to do with links. Try disabling Options > General > Show count of failed web requests for resources in the current tab, restart Firefox and try again. If that's the case, then I have no idea about the cause.

**Comment by olloff** [comment]
> Allow inspecting proxy used
> Show count of failed web requests

Sorry, none of it.   
Is there a quick way to suppress all errors/warnings raised by extension like debug switch?

**Comment by FelisCatus** [comment]
Sorry, I'm not quite familiar with the developer tools in Firefox and I don't know a way to suppress such information. But anyway, thanks for the feedback.

**Comment by olloff** [comment]
@FelisCatus I mean, suppress on the extension side. Opened https://github.com/FelisCatus/SwitchyOmega/issues/1173 to be more clear.

**Comment by olloff** [comment]
With https://github.com/FelisCatus/SwitchyOmega/issues/1171 fixed, this can be closed, unless another bug with excessive browser console use happens.
