### ISSUE TITLE
Add DEBUG setting

### ISSUE THREAD

**Issue by olloff** [FelisCatus/SwitchyOmega#1173]
I know this is minor enhancement, but most users win nothing from messages and warnings like:
```
Options << Options#applyProfile Array [ "<profilename>" ]  background.js:19:5
Options << Options#updateProfile Array [ Array[3] ]  background.js:19:5
Options << Options#updateProfile Array [  ]
Object { event: "proxyScriptLog", message: "Warning: Proxy script not initializ…", error: undefined, level: "warn" }
```

This messages are generating very often (this particular warning seems to depend on number of unique hosts) and have no use if extension works correctly. So it can be suppressed by some kind of verbosity/debug setting.

**Comment by FelisCatus** [comment]
`Proxy script not initialized` is not something we can suppress easily since it means that the extension is broken. #1171, for example, features proxy script not being initialized due to messaging issues. Still, there are a few harmless messages printed at startup when SwitchyOmega isn't ready yet. I can get those ones suppressed but I would rather wait until #1171 resolves.

`applyProfile` should only be printed after you apply a profile. This is not an error message and won't be included in Report Issue. It is there in the error log for good purposes. Some previous issues can't be located without such logs. It shouldn't be printed like crazy anyway and won't take up valuable memory. In fact users won't notice that unless they export the logs or take a look at the console.

I'm not convinced enough to add a debug switch since the messages are not overwhelming and won't annoy anyone when they are not "debugging" using Console or Save Error Log. Yes, if everything works fine they win nothing but they don't lose anything. On the other hand, when it doesn't work everyone lose a lot. Explaining about turning on verbose mode and restarting the browser is quite tiring, not to mention that if options page itself doesn't work properly then we cannot even turn on the switch.
