### ISSUE TITLE
The plugin seems to report resources blocked by adblocker as failed to load

### ISSUE THREAD

**Issue by fktpp** [FelisCatus/SwitchyOmega#1191]
Dear developer,

I am really appreciated you design such a great plugin. I am SwitchOmega user on both chrome and firefox.

As title, Just find a issue that do not exist on chrome version. 

I have adblocker and switchomega running side by side. While on chrome, switchomega is very smart about what was blocked and what was really not able to load through the current select proxy(at least in my view).

But on firefox, the plugin seems confused by the adblocker, where it trying to report adblocker blocked resource as not loadable view current proxy. This result same number draw on both adblocker icon and switchomega icon. 

All in all,
Thanks for the great plugin.

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://resources.jetbrains.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
This is due to the differences between webRequest API between two different browsers. On Chrome, blocked requests are considered errors and `onErrorOccurred` will be triggered. Therefore, we can easily ignore these requests. On Firefox, blocked requests do not trigger any webRequest event at all, which means we cannot differentiate them from timed-out requests.

I will keep this open just in case anyone is wondering. But I think it's better if someone or myself can open an issue at Bugzilla and start the conversation.

**Comment by FelisCatus** [comment]
These requests are now reported as `NS_ERROR_ABORT` in `onErrorOccurred`, enabling the fix above.

A release is coming soon.

**Comment by FelisCatus** [comment]
v2.5.3 submitted for review on AMO.

**Comment by FelisCatus** [comment]
Please update to latest Nightly build (>= 2017-09-18) and latest SwitchyOmega >= 2.5.4 for the fix.

**Comment by fktpp** [comment]
Great! it was fixed.
