### ISSUE TITLE
HTTPS proxy auto auth

### ISSUE THREAD

**Issue by nutinshell** [FelisCatus/SwitchyOmega#1195]
Doesn't work, always prompt login window.

SwitchyOmega 2.5.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by FelisCatus** [comment]
Is it just a few when Chrome is starting? If it is just at startup, please just click on cancel and it will still work on websites opened later. If it pops up the login window every time you open a new website, please read on.

First, try right clicking on the extension icon, and select Save error log. See if you can find `ProxyAuth` entries there. If you see entries but it still doesn't work, please double check your username/password. There have been reports where special characters break the authentication as well. The error log contains no confidential information and please feel free to post it there when in doubt.

If you don't see `ProxyAuth` entries there, then I will need to see your configurations to debug. Before doing anything, please change the proxy hosts, ports, usernames and passwords to random characters to protect your privacy. Then, in Options > Import/Export, create a backup file and upload it here. Also, it would be beneficial to specify the proxy server software you are using. For example, is it squid? Or stunnel around a normal HTTP proxy?

**Comment by nutinshell** [comment]
Hi, @FelisCatus it's Firefox, not Chrome, tell me if still need to check log and export config.

**Comment by FelisCatus** [comment]
Sorry, I meant Firefox. Yes, please still check the logs and export config.

**Comment by FelisCatus** [comment]
v2.5.3, which contains authentication support, has been submitted for review on AMO.

**Comment by WhiteWolf-One** [comment]
> Is it just a few when Chrome is starting? If it is just at startup, please just click on cancel and it will still work on websites opened later. If it pops up the login window every time you open a new website, please read on.
> 
> First, try right clicking on the extension icon, and select Save error log. See if you can find `ProxyAuth` entries there. If you see entries but it still doesn't work, please double check your username/password. There have been reports where special characters break the authentication as well. The error log contains no confidential information and please feel free to post it there when in doubt.
> 
> If you don't see `ProxyAuth` entries there, then I will need to see your configurations to debug. Before doing anything, please change the proxy hosts, ports, usernames and passwords to random characters to protect your privacy. Then, in Options > Import/Export, create a backup file and upload it here. Also, it would be beneficial to specify the proxy server software you are using. For example, is it squid? Or stunnel around a normal HTTP proxy?

You should perhaps 'star' this and/or put something in wiki on this.

I have been getting a lot of such popups, especially when opening Chrome. My guess has been that Chrome is attempting to restore tabs before SwitchyOmega has a chance to inject the proxy settings for that tab.

* Therefore "If it is just at startup, please just click on cancel and it will still work on websites opened later." is very good to know, and would save much user aggravation to so know. e.g. At startup when seeing this, press F5 (or Shift-F5, ignoring cache), and should be good to go. (?)

Further, I get this many times during use - my speculation has been the proxy server has dropped and is no longer accepting connections. My speculation here is that Chrome doesn't understand that / assumes lack of response is due to incorrect or unaccepted authentication and so prompts again. Therefore, when receiving this, and cancel doesn't work after several tries - the proxy is down and time to change proxy settings. (?)

Both of these / this sort of information, would be welcome within the wiki, and / or perhaps reference to the wiki in the chrome extensions add/on page, and/oor extension's 'general' page.
