### ISSUE TITLE
Error opening input stream (invalid filename?) when selecting System proxy profile

### ISSUE THREAD

**Issue by olloff** [FelisCatus/SwitchyOmega#1213]
When _System proxy_ profile is being selected, corresponding error happens. Firefox prioritizes browser proxy settings (normally it ignores browser proxy settings in this mode).

[OmegaLog_1505040852476.txt](https://github.com/FelisCatus/SwitchyOmega/files/1290442/OmegaLog_1505040852476.txt)

```
Options << Options#applyProfile Array [ "system" ]  background.js:19:5
Options << Options#updateProfile Array [ Array[1] ]  background.js:19:5
Error opening input stream (invalid filename?): moz-extension://ee22ee96-8b93-453e-8710-e78b665d19f0/js/omega_invalid_proxy_script.js  ExtensionCommon.jsm:284
Object { message: "An unexpected error occurred" }  background.js:26:5
No matching message handler for the given recipient.  MessageChannel.jsm:632
```
Also, one message omits every time any profile being selected, but it seems to not affecting any user experience at all:
`unreachable code after return statement[Learn More]  profiles.js:118:4`

**Comment by FelisCatus** [comment]
Ideally I would like things to work in the following order:

1. Use settings from SwitchyOmega, unless `[System Proxy]` is selected.
2. [Pass control](https://bugzilla.mozilla.org/show_bug.cgi?id=1319630) to the next extension.
3. If all extensions pass, use the browser settings. (Not applicable on Chromium.)
4. Fall back to system settings.

In this way everybody gets a chance to provide settings. Also, this seems aligned with the [Proxy API design](https://docs.google.com/document/d/1W45o5X2bFRPrTaQDFp9IzTJ8njCVfEgyENS7i2owaUI/edit). 

Also, `[System Proxy]` is a misleading name. The real behavior is to clear the proxy settings and let the browser pass control to the next entity, whoever it is. I'd say renaming it, but `[Pass Control]` is at least equally confusing, especially for newcomers. Let me know if you have better suggestions.

For your reference, we've decided not use `"system"` proxy settings so that users can easily use other extensions without uninstalling SwitchyOmega. If they don't have any other extension, then the browser will indeed grab the system settings, so there should be no need of an explicit `"system"`. The decision was made even before SwitchyOmega was started based on discussion on SwitchySharp's issue tracker. Also, `"system"` is [not supported on Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1319630), yet.

----

However, there are a few blockers here:

1. When `"direct"` is selected, the browser settings are used. (#1212) (TODO: Verify if other extensions are also consulted?)
    * In my opinion this shouldn't be the case once we have `"pass"`.
2. Currently, [passing control](https://bugzilla.mozilla.org/show_bug.cgi?id=1319630) to the next extension is not implemented in Firefox, and unlikely to be implemented in Chrome.
    * SwitchyOmega currently relies on `chrome.proxy.settings.clear()` or `browser.proxy.unregister()` to clear the proxy settings.
    * If those are not available, setting an invalid proxy script is used as a workaround, leading to the error you see.
    * None of the ways above can be used on a request-by-request basis. Therefore, `[System Proxy]` cannot be used in Switch Profiles.

**Comment by olloff** [comment]
Thanks for the awesome clarifying post, this was really an eyes-opener for me.
