### ISSUE TITLE
OCSP stapling bypasses proxy settings

### ISSUE THREAD

**Issue by mosajjal** [FelisCatus/SwitchyOmega#1244]
Hi.
I have no internet connectivity other than my proxy, and I started to see HTTPS websites (mainly gihub and t.co) timeout after a period of time. I use chromium  61.0.3163.100 (Developer Build) (64-bit) on Arch linux.
After digging around and using proxychains to run chromium, I saw a request from the browser to `ocsp.digicert.com` so I assumed this URL is being opened and checked before Proxyswitch. 

Is there a workaround to this problem ? 
regards

**Comment by FelisCatus** [comment]
SwitchyOmega does not send any requests apart from rule lists that you configure it to use. In other words, that request is not made by SwitchyOmega.

For your reference, `ocsp.digicert.com` contains the certification revoke list as far as I can tell. Probably Chrome has decided it should check the CRL before it visit any HTTPS website. The behaviors cannot be controlled by SwitchyOmega.

Instead of using proxychains, you can try to add a rule in your Switch Profile to allow `ocsp.digicert.com` to go through `[Direct Connection]` while directing everything else to your proxy. I cannot guarantee that would work for you though. As far as I can tell, using proxychains completely defeats the purpose of SwitchyOmega or similar proxy configuration extensions.

**Comment by mosajjal** [comment]
I am not planning to use proxychains as my main Proxifier. Just used it to see the requests being made from Chromium. I do not use SwitchyOmega in AutoSwitch mode and I use it for every URL. But still, oscp.digicert.com somehow bypasses it. I'll try it in AutoSwitch mode and will report the resutls

**Comment by klaaktu** [comment]
Sorry for commenting on an old issue, but I've also run into this issue a while back. `ERR_CERT_UNABLE_TO_CHECK_REVOCATION`
It seems Chrome does bypass proxy setting from SwitchyOmega: 
https://stackoverflow.com/questions/34865894/warnings-about-insecure-elements-on-some-https-sites-in-chrome-but-no-such-ele
https://bugs.chromium.org/p/chromium/issues/detail?id=583021
> you need to ensure that your Windows User-level proxy settings are appropriately configured ... which requires ensuring that your WinHTTP Proxy Settings are set

Occasionally websites loads partially or slowly when Windows proxy setting is unset, but idk if it's related since my connection isn't really stable and Chrome likes to read from cache...
