### ISSUE TITLE
CRITICAL - Proxy settings lost during recent update

### ISSUE THREAD

**Issue by PrabakaranSK** [FelisCatus/SwitchyOmega#1248]
After recent update, SwitchyOmega plugin is now showing only below 2 profiles  (even tried to restore from earlier backup which had my custom proxy profiles but they didn't show up)-

1) "proxy"
2) "auto switch"

PFA screenshot.

Hence auto proxy switching is not working for us, rendering the plugin completely unusable.  Please look into it and resolve on priority.

![switchyomega_issue](https://user-images.githubusercontent.com/10431329/31543656-c159779a-b034-11e7-88a4-dda4dd552564.jpg)

**Comment by EcoleKeine** [comment]
same problem with my chrome and chromium

**Comment by FelisCatus** [comment]
@PrabakaranSK @EcoleKeine Would you mind uploading your profile backups? That would help greatly on reproducing the problem here. Make sure you edit those backup files using a text editor and change the proxy server to dummy IP/ports though.

Also, you can also try importing the backup and then right click on the icon and select "Save error log".

**Comment by EcoleKeine** [comment]
I fix it myself

我自己解决了
导入失败的原因是OmegaOptions.bak里-quickSwitchProfiles中包含了null导致导入失败

@FelisCatus @PrabakaranSK
solution:
remove "null" in "-quickSwitchProfiles" prop
in OmegaOptions.bak file :
"-quickSwitchProfiles": ["proxy",null]
to
"-quickSwitchProfiles": ["proxy"]

**Comment by FelisCatus** [comment]
Let me add a check for that.

**Comment by FelisCatus** [comment]
Fixed in v2.5.6. I have no idea how the null values got there though.
