### ISSUE TITLE
Failed to Change/Create Mode

### ISSUE THREAD

**Issue by momoblydblk** [FelisCatus/SwitchyOmega#1332]
While I tried to switch from one of the mode to "Direct Connect", it didn't work as I expected.
Also, I tried to create a new a mode, I couldn't save my change to it.
PS: Log exported attatched below.
Thanks.

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
[OmegaLog_1514255098666.txt](https://github.com/FelisCatus/SwitchyOmega/files/1586419/OmegaLog_1514255098666.txt)

**Comment by FelisCatus** [comment]
When you select Direct Connection in SwitchyOmega, Firefox may still use your proxy settings in your Firefox preferences, system settings (e.g. IE's proxy settings on Windows) and so on. This cannot be fixed on SwitchyOmega's side. Please clear Firefox proxy settings and system proxy settings.

What happens when you press the save button? Could you please export a log file right after you clicked on the button?

**Comment by FelisCatus** [comment]
Please try v2.5.9 first. It may fix your problem. If not, please export the log in v2.5.9 as described above.
