### ISSUE TITLE
Broken icon in Firefox 58.0

### ISSUE THREAD

**Issue by anon88391** [FelisCatus/SwitchyOmega#1357]
The extension icon is bugged and entirely white in the newest Firefox 58.0.
https://i.imgur.com/NxeinR5.png

**Comment by FelisCatus** [comment]
Could you please right click on the icon and select "Save error log"? Having the log here definitely helps.

**Comment by haiwx** [comment]
I noticed, because of  **privacy.resistFingerprinting**  , you can chang it to **false** in **about:config**  
> [Firefox 58 warns you if sites use Canvas image data](https://www.ghacks.net/2017/10/28/firefox-58-warns-you-if-sites-use-canvas-image-data/)

**Comment by FelisCatus** [comment]
SwitchyOmega is using canvas to draw icons and apparently that's what broke it. A canvas is needed because the icons can come in any icon combinations.

In other browsers blocking canvas data, SwitchyOmega will fall back to the static, non-color-changing icon if it throws when trying to access canvas. Firefox is the first browser I've ever seen to return a blank image instead and I don't know what to do now.

Please see the Firefox issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1412961

**Comment by FelisCatus** [comment]
In v2.5.10, the SwitchyOmega icon will stay the default blue icon if you have `privacy.resistFingerprinting` set to true. It won't change based on profile colors but at least it won't become empty.

Please subscribe #1362 for the real solution.

**Comment by FelisCatus** [comment]
I believe this is fixed in Firefox 62. Note that it can still fail on modified / flagged versions of Chrome that disables canvas even for extensions.
