### ISSUE TITLE
有加密的代理已在设置中添加了账号密码，每次打开新网页还是需要输入账号密码

### ISSUE THREAD

**Issue by FaintGhost** [FelisCatus/SwitchyOmega#1375]
RT

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.168 Safari/537.36

**Comment by radaiming** [comment]
Looks Proxy-Authorization is not sent, a simple http server in golang to echo request headers:

```package main

import (
	"encoding/json"
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		headers, _ := json.MarshalIndent(r.Header, "  ", "  ")
		fmt.Fprintf(w, string(headers))
	})

	http.ListenAndServe(":8000", nil)
}
```

Then I create a new profile with "Proxy Authentication" filled:

![screenshot_2018-02-21_22-34-42](https://user-images.githubusercontent.com/1522741/36485679-a73a1240-1757-11e8-86db-95a850923aa9.png)

If I visit site via this proxy, I get this:

```
{
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
    ],
    "Accept-Encoding": [
      "gzip, deflate"
    ],
    "Accept-Language": [
      "zh,en-US;q=0.9,en;q=0.8"
    ],
    "Cache-Control": [
      "max-age=0"
    ],
    "Proxy-Connection": [
      "keep-alive"
    ],
    "Upgrade-Insecure-Requests": [
      "1"
    ],
    "User-Agent": [
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36"
    ]
  }
```

SwitchyOmega 2.5.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by FelisCatus** [comment]
@radaiming If the proxy server returns 401, which is the case for most password protected proxies, Chrome will ask SwitchyOmega for credentials, and then retry the request with Proxy-Authorization. This is a Chrome behavior and not controlled by SwitchyOmega. One can verify this by making the test server return 401 and the necessary headers as per HTTP specification.

Now, what OP asked is a different issue. In OP's case, the proxy server is behaving correctly, SwitchyOmega most likely provided the credentials, but the credentials are not deemed valid by the proxy server, which is why Chrome falls back to the popup window. First, please double check the credentials. Second, it is known that some special characters won't work even if an extension returns it correctly (#111), but entering it through the popup is a different story. In that case, SwitchyOmega has no way to fix it.

**Comment by radaiming** [comment]
@FelisCatus Really thanks for paying time to explain, actually I was testing my proxy which won't return 401 when authorization fails, and if returns 401, the proxy works :)
