### ISSUE TITLE
Socks5 authentication  in chrome

### ISSUE THREAD

**Issue by IranianSmile** [FelisCatus/SwitchyOmega#1455]
can't set socks5 with authentication user and password in chrome extension
it's work fine in firefox

![snag-1377](https://user-images.githubusercontent.com/17881816/39453793-cc7b9360-4cec-11e8-91d7-827e94793f92.jpg)

**Comment by FelisCatus** [comment]
See [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#why-cant-i-use-usernamepassword-authentication-for-socks-proxies).

**Comment by FelisCatus** [comment]
Base on my testing, FoxyProxy allows you to enter username / password on the options page, but they are never applied for SOCKS5 authentication. One interesting experiment to do would be to change the password to an invalid one on FoxyProxy (or even uncheck authentication) and see if it still connects. If it does, then your SOCKS5 proxy server does not require authentication at all.

If it is that case, then please try entering the exact server and port in SwitchyOmega without any credentials on the first row ONLY (leave the three rows below as `(use default)`) without any authentication to see if it works.

**Comment by FelisCatus** [comment]
I've tried simple-socks with FoxyProxy and it would not work no matter what configuration I put in.

I could need some help on reproducing the issue. Could you please let me know what your FoxyProxy configuration looks like and what proxy server software you are using? You can take a screenshot of your FoxyProxy profile page but black out your server address, username and password.

**Comment by FelisCatus** [comment]
Also, which FoxyProxy are you using? I see multiple versions on Chrome Web Store. Could you please kindly point me to a link to the one you are using?

**Comment by FelisCatus** [comment]
Just in case -- which Chrome version are you using? Please let me know if you use another Chromium-based browser or a fork, and I'll see if i can support that.

**Comment by IranianSmile** [comment]
https://chrome.google.com/webstore/detail/foxyproxy-standard/gcknhkkoolaabfmlnjonogaaifnjlfnp


[image: SNAG-1399.jpg]
[image: SNAG-1400.jpg]

**Comment by FelisCatus** [comment]
Okay, I think now I get it. In FoxyProxy, you need to check "SOCKS proxy" on the second line to make it a SOCKS proxy. If you don't check it, then it configures an HTTP proxy.

Therefore, I believe your proxy is actually an HTTP one. Please try selecting `HTTP` and fill in only the first row in SwitchyOmega, and leave the following rows blank. This would allow you to enter your credentials. Let me know if that works.

**Comment by IranianSmile** [comment]
I have HTTP proxy too
But it's on different port!
So in your idea, Socks and Http most be on same port,and it's not. My socks
5 proxy has an unique port.
I used http proxy on switchyOmega, it's fine. But socks is so much better,
safer, and fastest. I don't know foxyProxy use any tricks or not, it
doesn't matter when it work with socks5 by authentication.

**Comment by xiaominggpT7890** [comment]
Chrome SOCKS5 Authentication Issue
Google Chrome does not support SOCKS5 authentication (username and password) natively. This is a known limitation, officially documented as a bug: https://crbug.com/1309413. Despite attempting various extensions, this functionality remains unsupported due to inherent limitations in Chrome's design.

Official Confirmation
The official Chrome team has confirmed that SOCKS5 with authentication is not supported by default. As such, users cannot configure SOCKS5 with credentials directly through Chrome's built-in settings or extensions.

Alternative Options
Third-Party Browsers with SOCKS5 Authentication
Some third-party browsers, like [Easy Browser](https://ebrower.com/) (EasyBR), have already integrated SOCKS5 authentication (username and password) into their functionality. These browsers also support HTTP and HTTPS authentication and offer a wide range of customizable proxy settings.

Custom Chromium Compilation
If you need full control over SOCKS5 authentication features, the only viable method is to modify Chromium's source code yourself. This allows advanced users to implement SOCKS5 with authentication manually, though it requires coding expertise.

Recommendation
If you are looking for an easy-to-use solution, Easy Browser (EasyBR) offers free access with built-in SOCKS5 authentication capabilities and customizable options. For those willing to invest time and expertise, compiling a custom Chromium build is an alternative way to enable this functionality.
