### ISSUE TITLE
Startup profile when multiple users open Chrome

### ISSUE THREAD

**Issue by Mori79** [FelisCatus/SwitchyOmega#1468]
Steps to reproduce the issue:
1. Open two separate Chrome windows using two different Google accounts.
2. Now choose a proxy profile on one of them — something different from what you've selected as the default _Startup Profile_.
3. Close the window and reopen it.

You'll see the same proxy profile rather than the default startup profile.

SwitchyOmega 2.5.9
Chrome/66.0.3359.170 (Official Build) (64-bit)

**Comment by FelisCatus** [comment]
The only way this can happen is because SwitchyOmega is not actually restarted. Could you please check a few things please?

First, check if your other user is still running in the background due to background apps. You may find icons in your system tray if that's the case. If so, please close those and try again.

Second, it may be the case that Chrome is still keeping the SwitchyOmega background page open for a while. Try closing all windows of the other user (including background apps) and wait a few minutes before you retry.

If either is the case, there is no way SwitchyOmega can fix this. If not, I can probably experiment a little bit to see what's happening here.

**Comment by Mori79** [comment]
> First, check if your other user is still running in the background due to background apps. You may find icons in your system tray if that's the case. If so, please close those and try again.
That's not the case.

> Second, it may be the case that Chrome is still keeping the SwitchyOmega background page open for a while. Try closing all windows of the other user (including background apps) and wait a few minutes before you retry.
I tried it to no success.

> I can probably experiment a little bit to see what's happening here.
Yes, please do so.

**Comment by FelisCatus** [comment]
I've tried this and the SwitchyOmega background page is never unloaded when you close just one user. Therefore, to SwitchyOmega, it is not restarted.

One way to work around this is to track all the windows and see if they are all closed. I don't think this is a good thing to do for SwitchyOmega though. Considering the added complexity and the number of corner cases (including background extensions and apps that does not use a window), I will have to reject such a feature request.

Please, anyone, let me know if there is a better solution.
