### ISSUE TITLE
Extension is not working now, Proxies are fine but not working with the extension

### ISSUE THREAD

**Issue by Hukmaram28** [FelisCatus/SwitchyOmega#1618]
Extension is not working now, Proxies are working but not working with the extension. I checked yday and it was working

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by FelisCatus** [comment]
What do you mean by "not working"? Which part exactly is not working? Please describe the steps to reproduce the issue, and what is different from the expectation.

If you are using Auto Switch, try selecting your proxy profile instead and check if everything works fine under your proxy profile. This helps to identify any issue with the network or your proxy. If none of the websites load with the proxy profile, then please check if your proxy server is running and correctly configured with the right host / port. [This FAQ entry](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#i-cant-even-access-the-internet-when-i-enable-switchyomega) contains detailed instructions on troubleshooting the proxy.

Now, if your proxy profile works on its own, but Auto Switch does not use your proxy when you would want it to, please check whether the right rules are in place. Hovering over the SwitchyOmega icon in the toolbar shows what rules are checked in order to determine the proxy of the page. Sometimes, you will need to add rules to your switch profile and sometimes you would benefit from a rule list, which is a predefined set of rules maintained by someone else. If you believe the rule list should include / exclude a certain website, please contact the rule list maintainer.

**Comment by Hukmaram28** [comment]
Don't know what happened that time, for few hours it was not working for
me, then I checked again and it working fine,  Still working fine. Thanks
