### ISSUE TITLE
Bug in Proxy Profile when using authentication feature

### ISSUE THREAD

**Issue by sebastian312** [FelisCatus/SwitchyOmega#1631]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Vivaldi 1.15.1147.64
Ubuntu 18.04.1

### Problem description / 问题描述

When using several proxy profiles there exist a bug in some condition:
1. Proxy Profile **A**: HTTP Proxy IP: _1.2.3.4_, Proxy Port: 8080, Username: **admin**, PW: ***
2. Proxy Profile **B**: HTTP Proxy IP: _1.2.3.4_, Proxy Port: 8080, Username: **internal**, PW: ***

As you can see both profiles have the same IP address.

My Switch Profile contains some rules which decide to which Proxy Profile request is sent:
e.g.

Condition Type: Host Wildcard
Condition Details: *.management.local
Profile: Proxy Profile **A**

Condition Type: Host Wildcard
Condition Details: *.internal.local
Profile: Proxy Profile **B**

The following issue can be seen:
Credentials (Username: internal) from the last proxy profile will always be used.

In my opinion there is a bug when using several proxy profiles that use the same Proxy IP (Proxy Port) configuration but differen users.

I noticed the following behaviour: When using a different Proxy IP for example in Proxy Profile **A** everything is used as expected (I monitored network traffic with wireshark)

#### Expected behavior / 期望发生的情况

Username from Proxy Profile should be used.

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

Last username from Proxy Profiles (which have the same Proxy IP) is used by SwitchyOmega.

**Comment by FelisCatus** [comment]
Yes I can confirm this. Unfortunately, this is the best that SwitchyOmega can do, given that Chrome will remember the credentials for a certain host:port and will NEVER ask SwitchyOmega again in the next few minutes, or until SwitchyOmega is restarted. This behavior is observed no matter a popup dialog is used, or an extension is involved.

At this point, I'll suggest a workaround of making them appear as different proxies to Chrome. First, in your hosts file, add a line that reads `1.2.3.4. admin-proxy internal-proxy`. This will make both `admin-proxy` and `internal-proxy` resolve to `1.2.3.4` on your device. Then, you can use those two domain names in SwitchyOmega, instead of the IP address. I believe this should trick Chrome into thinking that they are different.

Let me know if it works.
