### ISSUE TITLE
Support proxy username/password for PAC configuration

### ISSUE THREAD

**Issue by dhergert** [FelisCatus/SwitchyOmega#190]
It would be nice if you could specify a username and password to be saved with a proxy configuration for PAC.

**Comment by FelisCatus** [comment]
Cool, but what if the PAC returns different proxy servers for different URLs?

**Comment by dhergert** [comment]
That's a good point. Every enterprise I've worked at, there has been only one corporate proxy for external access so that's why I only thought of one. If that's less common than maybe it makes less sense.

**Comment by FelisCatus** [comment]
Also, the current implementation of proxy authentication checks the proxy server address asking for the credentials. This works great with Fixed Proxy Profile, but may cause issue with PAC scripts. SwitchyOmega has no way to tell the possible set of proxy servers returned by the PAC in advance, since the PAC script is JavaScript, and it can do whatever it like (string operations, dice rolling, etc.).

Shall we just provide the same pair of username and password regardless of the proxy server for PAC profiles? But... wouldn't that make it less secure?

P.S. I think it's pretty common for a PAC server to choose between only one proxy server and direct connection. But we can't assume that just because it's common.

**Comment by gaocuo** [comment]
我觉得能对所有的 Proxy auth 返回一个固定的用户名密码已经足够应付99%的状况了，毕竟在现实中，一个 PAC 返回的多个 Proxy server list 里面，对于每台不同的 Proxy Server需要不同的用户名密码的情况几乎没有。

**Comment by FelisCatus** [comment]
I'm going to add support for this, with the following logic applied:

* You can only provide one pair of username and password per PAC profile, and
* That pair of username/password is used regardless of the PAC result, whenever there's a challenge from any proxy server.
  * (!) This could lead to username/password being sent to an unexpected and untrusted proxy server, which is provided by the PAC script.
* If a Switch Profile references a PAC profile, the credentials of the PAC profile is used as a fallback. If multiple PAC profiles are referenced, all the credentials will be attempted until one of them works.
  * A Switch Profile is said to "reference" a PAC profile, when the PAC profile appear anywhere in the settings of the Switch Profile.
  * The PAC profile don't have to be actually selected according to the configured conditions.
  * The reason behind using "referencing" instead of "selecting" is purely technical. (The extension cannot know which server is actually being selected.)
  * (!) This could cause the username/password of a PAC profile to be sent to a proxy server specified in a Fixed Proxy Profile under certain scenarios.

@dhergert  Does that sound reasonable?

**Comment by dhergert** [comment]
Yes! I think it will help the people in corporate environments.  It's not
like I'm using a wpad, which could reference a proxy I'm not familiar with
... I've explicitly entered the pac file directly so should trust my
credentials being sent to any proxy that it may reference.

Very cool!

On Wednesday, January 28, 2015, FelisCatus <notifications@github.com> wrote:

> I'm going to add support for this, with the following logic applied:
>
>    - You can only provide one pair of username and password per PAC
>    profile, and
>    - That pair of username/password is used regardless of the PAC result,
>    whenever there's a challenge from any proxy server.
>       - (!) This could lead to username/password being sent to an
>       unexpected and untrusted proxy server, which is provided by the PAC script.
>     - If a Switch Profile references a PAC profile, the credentials of
>    the PAC profile is used as a fallback. If multiple PAC profiles are
>    referenced, all the credentials will be attempted until one of them works.
>       - A Switch Profile is said to "reference" a PAC profile, when the
>       PAC profile appear anywhere in the settings of the Switch Profile.
>       - The PAC profile don't have to be actually selected according to
>       the configured conditions.
>       - The reason behind using "referencing" instead of "selecting" is
>       purely technical. (The extension cannot know which server is actually being
>       selected.)
>       - (!) This could cause the username/password of a PAC profile to be
>       sent to a proxy server specified in a Fixed Proxy Profile under certain
>       scenarios.
>
> @dhergert <https://github.com/dhergert> Does that sound reasonable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FelisCatus/SwitchyOmega/issues/190#issuecomment-71793140>
> .
>


-- 
-Dave

**Comment by FelisCatus** [comment]
@dhergert Cool then. I'll start working on it.

**Comment by FelisCatus** [comment]
Credentials for PAC scripts is supported as of v2.3.1, with proper security warnings shown on usage. Check out the new padlock button besides the "PAC Script" section.

v2.3.1 已经支持 PAC 脚本的用户名密码。使用时，会显示相关安全警告信息。设置的位置在"PAC脚本"一节右侧，新增小锁图标按钮。

**Comment by ciznx** [comment]
Just to remind, please confirm not to send the username / password pair during secure requests (such as HTTPS requests, websockets  connections, etc). Because proxy server can not and don't need to decrype these requests, so these credentials may be send to destination server unexpectly if you attach credential during secure requests.
As an exception, proxy authorization info should be attach for the negotiation requests before secure requests (like CONNECT request before HTTPS or Upgrade request for secure websockets)

**Comment by FelisCatus** [comment]
@ciznx This is controlled by Chrome and does not need special attention on SwitchyOmega's side. I believe Chrome is already doing so by only responding to proxy authentication requests but not target server.

**Comment by JackJiaJJ** [comment]
@FelisCatus @gaocuo @jijiechen @dhergert Hi guys, I get the same issue, from the conversation history, seems this function has been implemented, I wonder how to specify the user/password into the PAC file ? many thanks !

**Comment by unoexperto** [comment]
Where exactly username/password is in the UI ? I cannot find it. I have 2.5.9 version.
