### ISSUE TITLE
Wrong profile for redirected URL's

### ISSUE THREAD

**Issue by deathfan** [FelisCatus/SwitchyOmega#205]
Hi,

I have the switch rule with the following configuration:

- "Default" - Proxy1,
- "Rule list rules" - Proxy2.

Rule list has AutoProxy format and contains the following text:

*.sap.com
*.microsoft.com
*.ibm.com
*.sap-ag.de

The switch rule works well for all sites if they is called directly. But when I call "service.sap.com" it makes redirection to "websmpxxx.sap-ag.de". Since I have the separate entry the Switchy should go through "Proxy2" but it's goes by wrong way - via "Proxy1".

Please check it and give feedback.

Windows 7 x64 Pro
Google Chrome Version 39.0.2171.95 m
Proxy SwitchyOmega 2.2.13

Best regards,
Alexander.

**Comment by FelisCatus** [comment]
Would you please export a settings backup file and upload it to gist.github.com? The settings are too complex to reproduce just from your comments...

**Comment by deathfan** [comment]
I've made backup and put it onto gist:
https://gist.github.com/3dfce5e67a3dea31432d.git

**Comment by FelisCatus** [comment]
Are you using profile Auto Switch with ELD_wifi? You should chain them together by setting the default profile of Auto Switch to `ELD_wifi`. Then switch to the `Auto Switch` profile and you will be fine.

**Comment by deathfan** [comment]
I thought if I set the profile ELD_wifi (see image below) then it the one will be using independently of all other profiles (Auto switch and others). 

![image](https://cloud.githubusercontent.com/assets/10560228/5778124/0481a51a-9daa-11e4-8371-5838dadb581b.png)

**Comment by FelisCatus** [comment]
Profiles are always used independently unless explicitly chained (e.g. using one profile as the result of another profile). A chained configuration will work better here since you want both your rules in `Auto Switch` and the rule list in `ELD_wifi`.

**Comment by deathfan** [comment]
I'm not using chain's and don't want to. I don't want to use both of my rules simultaneously and not using it - I'm using independently by manual choosing. BTW "Auto switch" rule has no any entries for sap.com and sap-ag.de hosts so it isn't correlates with my problem I think.

**Comment by FelisCatus** [comment]
Thanks for the clarification. I misunderstood your intention earlier. It has nothing to do with the "Auto switch" profile. Sorry for that.

If I'm not mistaken again, you are expecting an AutoProxy rule `*.sap.com` to match the website of `service.sap.com`. But actually, it didn't match and the default rule is used instead. Right?

In that case, may I ask about the full URL of the website in question?

Also, please note [AutoProxy rules are pretty complex](https://autoproxy.org/en/Rules), and they only match HTTP instead of all protocols (HTTP, HTTPS and FTP). AutoProxy rules are only provided for compatibility, not for daily proxy switching needs. I would recommend disabling the rule list and trying again with conditions (like the `1.1.1.1` condition above, but replace the text with `*.sap.com`).

**Comment by deathfan** [comment]
Hi FelisCatus,

I haven't found a way to "disable" the "AutoProxy" rule so I completely deleted it.

But the problem is still persists: if I try to open "http://service.sap.com" it redirects me to "https://websmpXXX.sap-ag.de" and "Home_http" profile is used instead of "Eldorado".

**Comment by FelisCatus** [comment]
No, it's not about redirects.

As I have pointed out earlier, AutoProxy rule lists **does NOT** match HTTP**S** URLs by defaults. Therefore, the `*.sap-ag.de` AutoProxy rule will not match the `https://websmpXXX.sap-ag.de` URL.
This is by AutoProxy's design, which fully respected by SwitchyOmega for compatibility. It just happened to work for microsoft.com because Microsoft does not turn HTTPS on by default.

Really, you should be using conditions, which is native in SwitchyOmega and does not contain such surprises. (It matches URLs of all protocols including HTTPS as you would expect.) Or, read [all about AutoProxy rules more carefully](https://autoproxy.org/en/Rules) if you want to work with them.

I would also like to suggest that plain text-based editing for switch conditions would be the real solution to your real problem, which is tracked at #80. (The issue contains a lot of off-topic discussion in Chinese that should be ignored though.) The basic idea is to edit switch conditions as easily as rule lists, removing the need to rely on a particular foreign rule list format.

**Comment by deathfan** [comment]
Hi,
I've arranged my Rule list text according to Switchy format and my issue has resolved. Thank you!
