### ISSUE TITLE
DNS requests should go via a proxy

### ISSUE THREAD

**Issue by dylanpiergies** [FelisCatus/SwitchyOmega#222]
I'm not entirely sure if this is possible to implement in an extension. Chrome is presumably using the operating system's resolver to resolve host names. Implementation of this feature is unlikely to be trivial. For the paranoid, though, it's an important consideration.

At present, although HTTP traffic may be sent via a proxy server, queries to DNS servers are not. If possible, an option to make DNS queries via the proxy should be added.

**Comment by FelisCatus** [comment]
I believe this is related to DNS prefetch and cannot be controlled by extensions. DNS prefetch can be configured in Chrome settings (something labeled as prediction). Try turning it off to see if it helps. The `chrome://net-internals` page can show you the events related to DNS and network requests.

On the other hand, DNS requests are always tunneled through a SOCKS5 proxy. Try setting up a SOCKS5 proxy server if you have access to the server side.

I don't have much knowledge about Chrome network internals, and this extension is only doing configuration rather than tweaking packets. I would suggest posting to the Chromium issue tracker if you have more questions.

**Comment by FelisCatus** [comment]
I [documented about this in the project wiki](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy), with steps to avoid DNS request leaking. Please refer to that page if you are interested in this topic.

**Comment by meffect** [comment]
Found this via google. I noticed it possible to disable via extension now

![screenclip](https://cloud.githubusercontent.com/assets/1799758/20636477/b772c41c-b322-11e6-9ba8-0a6e77273487.png)

**Comment by FelisCatus** [comment]
Thanks. I believe new chrome APIs allow extensions to control privacy settings. I will dig into this once I have time.
