### ISSUE TITLE
My most favorite feature:  Sync settings across Chrome

### ISSUE THREAD

**Issue by a3c4x8** [FelisCatus/SwitchyOmega#226]
My most favorite feature:  Sync settings across Chrome.

I had used Proxy SwitchySharp for one year. But I always have a pain point. Since I have three Chromebooks and two Chromebox located in Beijing/Chengdu/Zigong, I have to make every setting change five times. Sometimes, I got five different settings version. As you know, import/export a setting file does not work perfect for my situation. Thanks God, sync settings across Chrome come true. We all know, sync everything through Google cloud is a great feature on Chrome browser/OS.

Thanks for your great work.

BTW, may I have your email? Do we have any planning solution for Android device? 

Have a nice weekend and wish SwitchyOmega a big success in the year of Goat. 

SwitchyOmega 2.3.0
Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36

**Comment by FelisCatus** [comment]
I can't believe that you are complaining that syncing isn't available when you are using the shiny new SwitchyOmega 2.3.0 with syncing just added as a big feature right now. ;)

Yes, you've read that right. Syncing is supported NOW!

However, syncing isn't enabled by default. You can opt in syncing on the Import/Export options page right now. And since you have five devices already configured, syncing must be turned on individually on each of your devices. Don't worry, it will be a one-time procedure though.

Once the first device is setup for syncing, its options are automatically uploaded to the cloud, available for downloading to the other devices. Downloading the synced copy will overwrite your existing configurations on the other devices, creating a unified and synced options via the cloud. Any changes on one of your devices will be automatically propagated to your other devices from this point.

**Comment by a3c4x8** [comment]
It's not a complaint. I just want to say thank you for the settings sync
feature. But I have not your email, so I had to show my strong appreciation
through this bug management tool.

Thanks for your great work.

**Comment by TotooriaHyperion** [comment]
LoL~~ I won't notice this amazing feature without this funny issue.
Thank you two guys ~

**Comment by xnervwang** [comment]
I have used SwitchyOmega for many years and this is the first time I know it has sync feature. I mean, I lost rules after I reinstalled system every time in the past...
