### ISSUE TITLE
Failed resources, add to proxy list

### ISSUE THREAD

**Issue by zzzgit** [FelisCatus/SwitchyOmega#2346]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1060733/208593572-b175f662-6ace-412f-a1ab-278103305a43.png">

Failed resources, 以前是直接有個按鈕，把他們加入到代理列表。現在這個按鈕為什麼改了？

**Comment by H-MAli** [comment]
So, this issue is rather prevalent in my setup.
The issue is I have set up all my traffic to go through a proxy server that I have, but have set some rules for some select domains to connect directly.
Let's assume "a.com" is among the sites that should be routed directly (and not through the proxy server). When visiting "a.com", if the website has made use of services such as various captcha services, web font services, website analytics services, etc. that require external script tags, the resource failed thingy gets triggered and the website's functionality gets affected.

I guess there should be an option or something that dictates any subsequent requests from "a.com" follow the same rule as it does.

**Comment by zzzgit** [comment]
> dictates

我的又回來了。

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1060733/232748042-2cd91d3c-9f6a-4262-82fc-7b5df1f755e3.png">

I guess，跟你的設置有關係。

<img width="866" alt="image" src="https://user-images.githubusercontent.com/1060733/232748354-2de6419b-8e60-4613-8eb0-6dfde93c52c6.png">
