### ISSUE TITLE
Local proxy attempting to download webpages as files instead of displaying them

### ISSUE THREAD

**Issue by doque** [FelisCatus/SwitchyOmega#258]
##### What's the problem? (e.g. The expected output and the actual output.)

When using a proxy that's running on localhost (127.0.0.1:8080), webpages that apply to an Auto Switch Mode Rule will not be rendered, but instead there is an attempt to download them. The file being downloaded is useless (only contains "0505 00" - see attached sample).

##### What steps will reproduce the problem?
1. Create new proxy running on localhost on a specific port
2. Create new AutoSwitch rule, or just use proxy for all sites 
3. Attempt to navigate to any site

##### What's your operating system and which version of Chrome/Chromium are you
using?
Google Chrome	40.0.2214.94 (Official Build) 
Revision	b631d0526afba969df4c66f3b6baed0759f8b814-refs/branch-heads/2214_85@{#8}
OS	Mac OS X 

I'd like to add that the proxy itself is working fine when using FoxyProxy. The app to open the local proxy is [SSH Tunnel](https://itunes.apple.com/us/app/ssh-tunnel/id734418810?mt=12).

**Comment by doque** [comment]
Attached file that the download creates (not really a png)

![download](https://cloud.githubusercontent.com/assets/1480751/5998143/854ba7b4-aac4-11e4-9265-445fb6f573e5.png)

**Comment by FelisCatus** [comment]
Thanks for letting me know some information about the proxy. Based on your description, it seems unlikely that the proxy server is malfunctioning. (SOCKS proxies do not modify HTTP headers and therefore can't trigger the file download in that way.)

I spent a lot of time searching in the chromium issue tracker the past few hours and have no luck finding relevant information.

With that being said, it is also very unlikely that SwitchyOmega is doing wrong because SwitchyOmega just sets Chrome settings instead of doing the actual network transport.

Please help to provide more information. Here are a few suggestions that may help you to diagnose the problem:

1. Try disabling SwitchyOmega along with any other extensions. Then restart chrome with the following flags: `--proxy-server="socks5://127.0.0.1:8080"`, with 8080 replaced by the port of your proxy.
  * You can also run Chrome with `--user-data-dir=/tmp/test` (and the proxy flags) to use a temporary and fresh new user data directory, leaving your original data directory completely untouched.
  * This method will set the proxy server directly without using any extensions. I suspect that would produce the same results. If so, it would narrow the cause of the issue down to the range of Chrome net internals, plugins and/or the proxy server.
1. Please check the `chrome://plugins/` page and see if there's any plugin that could cause the issue.
  * I've heard that [some download related plugins may cause similar issues](https://productforums.google.com/forum/#!topic/chrome/_cA0qdJ4LHI).
  * If you are not sure, just provide a brief list or screenshot of the plugins installed.
  * You can disable all the plugins and restart the browser and see if it helps.
1. You may try Chrome Beta or Dev to see if your issue can be resolved. Of course, this would only work if the issue is indeed caused by Chrome itself and get fixed in newer releases.

Note: Restarting an application on Mac is a more-or-less tricky thing but can be as simple as Command-Q. You may want to make sure that Chrome is fully closed, by ensuring that it does not appear any more on the force close dialog.

**Comment by doque** [comment]
After further research, I found that the proxy type setting wasn't set to SOCKS but to HTTP. Changing this resolved the issue completely. Sorry for the trouble.

**Comment by FelisCatus** [comment]
@doque I'm glad that it is working for you at last. And thanks for letting me know what would happen if a SOCKS server is mis-configured as HTTP. Well, I think I could be more helpful if someone else experiences similar issues ;)
