### ISSUE TITLE
it doesn't work on auto switch and thanks for fixing:)

### ISSUE THREAD

**Issue by ownstar** [FelisCatus/SwitchyOmega#279]
SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
Just saying that something "doesn't work" is not gonna help. Auto Switch is of course working in general because there are many users out there using this feature every day. However, things could break under certain circumstances, or you could have made mistakes in your configuration. In order to solve such problems, more information is needed. The following template can be a good start for you.

What's the problem? (e.g. The expected output and the actual output.)
(Bad: It doesn't work! IT DOESN'T WORK!!!!!!11)
(Good: I set up the switch conditions to use Proxy A for www.example.com, but I find it using Direct Connection instead. Steps in details follows.)

What steps will reproduce the problem?
1.
2.
3.

Please submit your settings backup file as an attachment.
 * You can export the backup file by clicking the "Make full backup" button
in the "Import/Export" tab in the options page.
 * Please submit your backup file, which is downloaded automatically, by uploading it to https://gist.github.com/

**Comment by gip0** [comment]
**Summary**
The way this chrome extension designed is not user friendly enough. I happened to spend several minutes figured it out. This instruction is for SwitchOmega 2.3.7, Feb 2015.

**Preparation**
1. a proxy, I used ssh -D
2. a rule list, which decides whether specific traffic going through proxy or not, I used [autoproxy list](http://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt)

**Steps**
1. Install SwitchOmega and open its setting panel
2. In *Interface* tab, set *Startup Profile* to *auto switch*
3. In *proxy* profile tab, add your proxy accordingly
4. In *auto switch* profile tab, check *Rule list rules* (default), set *Profile* of the **same row** to *proxy*
5. In *auto switch* profile tab, set *Rule List Format* to *AutoProxy*, paste the url above to the *Rule List URL*, hit *Download Profile Now* (This may require proxy in China)
6. You are all set, restart chrome if it does not work

**Comment by FelisCatus** [comment]
@gip0 Thanks for sharing. However these instructions does not belong to this issue (and may not suit well in the issue tracker). Besides, [a wiki page](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList) is already created with roughly the same steps in Chinese with screenshots and instructions. You may translate that into English if you want to help.
