### ISSUE TITLE
Request Define Shortcut Key

### ISSUE THREAD

**Issue by Masiha** [FelisCatus/SwitchyOmega#342]
Hi
Please add shortcut key for changing proxy
for example: Ctrl+1, Ctrl+2, ...
Regards

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
It is possible to open the popup menu with Alt+Shift+O. After that, you can press "?" to see the access key for each profile. For example, `1` for the first user-defined profile.After you memorize this key, you can use the key sequence `Alt+Shift+O`, `1` to switch to it.

Another solution would be using the "Quick Switch" feature, which avoid opening the menu altogether and let you cycle through a few profiles by just pressing "Alt+Shift+O".

P.S. Using Ctrl+1, Ctrl+2 and so on won't work because Chrome has already reserved those combinations for tab switching. (e.g. Ctrl+1 for the first tab.)
