### ISSUE TITLE
System config update

### ISSUE THREAD

**Issue by Clement-D** [FelisCatus/SwitchyOmega#434]
Hi,

I have recently migrate SwitchyProxy to SwitchyOmega (on Chrome).
In former version, selected proxy was updated in Chrome settings AND in system configuration.
Now, when SwitchyOmega, only Chrome settings and updated.
As a consequence, if I run an application that require internet access, I have to change system configuration (in ie network settings)

Is there any way to force SwitchyOmega to change system settings ?

Regards

Clement

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega is not a fork or update of Proxy Switchy!. Although SwitchyOmega follows a similar proxy configuration model and support almost all features of Proxy Switchy!, it does not attempt to change system proxy settings. Instead, it leverages the cross-platform Chrome Extension API to set the proxy settings in Chrome only. Such decision was made for the following reasons:

* Platform-specific code is needed for for every platform, including Windows, Linux and OS X.
* As a major contributor, I do not have time or skills to handle that. Besides, there are no active specialists in that area in the SwitchyOmega project.
* The code from Proxy Switchy! is not longer maintained after 2010, and is considered unstable for usage in current operating systems. Therefore such code cannot be reused in SwitchyOmega.
* Embedding native code in Chrome extensions requires too much permission and causes lots of trouble.
* The proxy settings in Chrome does not map 1:1 with those in the system. Not to mention the setting models also differ from OS to OS.

However, you can export the PAC script from SwitchyOmega and use that in almost all OS and other browsers. Just select a profile, and click on the "Export PAC" button and save the file in somewhere. You can then instruct the system to use this file for a system-wide proxy settings. You can export another profile to override the existing file and system-wide proxy settings should be automatically updated. However, export cannot be done without user interaction due to limited access of file system in Chrome extensions.
