### ISSUE TITLE
non-qualified names

### ISSUE THREAD

**Issue by TheTomahawk** [FelisCatus/SwitchyOmega#465]
When trying to access our intranet site as just http://intranet/, DNS lookup fails when SwitchySharp is active (it works if I put in the fully qualified domain name, but many links from other internal sites don't have domain added)

If I disable the plugin, the URL works fine (and also works fine in other browsers).

This is occurring on a Windows 8 machine with Chrome 41.0.2272.118 m (64-bit) and SwitchySharp 1.10.6

**Comment by TheTomahawk** [comment]
Having realised that SwitchySharp has been replaced by SwitchyOmega, I upgraded to the latest version available via Google Chrome.  The same issue occurs.

If I switch to 'System Proxy', it works fine.  The proxy settings I'm using via SwitchyOmega as copied from the system proxy settings, apart from the server name.  If I update the servername in the system proxy settings, everything still works as expected (via the system proxy), so it's not the proxy.

**Comment by FelisCatus** [comment]
This happens because Chrome sends the full unresolved URL with domain name to the remote proxy. (i.e. remote DNS resolving) and is not really related to the SwitchyOmega project.

Please note that this can be worked around send these requests without any proxy. You may need to use a new Switch Profile and add a rule to send them to "Direct Connection", while making the default profile your proxy profile. If you need to proxy all unqualified domains, you may find the "host levels" condition helpful (`1 ≤ host levels ≤ 1` for all domains without dots), which is only shown after you enable "Show advanced condition types" under "Interface" > "Switch Options".

**Comment by TheTomahawk** [comment]
Thank you.  That works a treat.
