### ISSUE TITLE
conflict with ultrasurf extension

### ISSUE THREAD

**Issue by geetered** [FelisCatus/SwitchyOmega#484]
ultrasurf extension
https://chrome.google.com/webstore/detail/ultrasurf-privacy-securit/mjnbclmflcpookeapghfhapeffmpodij?hl=en-US

**Comment by FelisCatus** [comment]
CONFLICTS: SwitchyOmega will conflict with other extensions trying to control the proxy settings. Such conflicts are caused by the design of the Chrome browser and thus cannot be avoided. When SwitchyOmega has a higher priority, it can be configured to voluntarily give back the control by selecting the [System Proxy] item in the popup menu. Otherwise, you will see a red badge on the SwitchyOmega icon indicating insufficient priority. Re-installing SwitchyOmega should raise its priority, providing a possible workaround.
