### ISSUE TITLE
Use GitHub Pages for report issue landing (使用 GitHub Pages 作为‘报告问题’的着陆页面)

### ISSUE THREAD

**Issue by celeron533** [FelisCatus/SwitchyOmega#584]
Current SO's right-click context menu **'report issue'** just redirect user to Git project's issue tracker which is good for IT-knowledge-based users. However, for other users, this may generate some duplicated, redundant or junk tickets.

For instance, in these days, while a part of users have upgraded their environment to Windows 10 & Chrome 45, SO became unusable. After several discussions, the community found some downloadhelper (Thunder(迅雷)) modified windows network related configuration which caused this issue. At the same time, large amount of tickets reported the same issue. Both users & developers spend a lot of time to tackle these questions although they are in the same topic.

In my opinion, it is better to modify current **'report issue'** menu, redirect it to an **FAQ page**, ask end-user try to solve the problem by themselves first.

**Comment by FelisCatus** [comment]
A Github page would serve the purpose well in my opinion. The page can show users the FAQ and ask users to provide more information. If the user decides to submit the issue, he or she can be then taken to the Github new issue form, with the debug information attached.

**Comment by FelisCatus** [comment]
An [https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ] page is ready with English and [Chinese](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) versions.

The problem is the FAQ page is not dynamic and cannot contain JavaScript code. Therefore, if we use that as the landing page, the associated information including version number and stack trace will be lost. A GitHub page will solve the problem.

**Comment by FelisCatus** [comment]
I'd like to keep this open to track the issue of using GitHub Pages to improve the issue reporting experience. Please let me know if you have different opinions.
