### ISSUE TITLE
The proxy settings are overruled by policies

### ISSUE THREAD

**Issue by mcaigjt** [FelisCatus/SwitchyOmega#642]
Installed SwitchyOmega on my Chromebook Pixel, but when I try to click on the button, it says that the proxy settings are overruled by policies and I need to contact my administrator.

SwitchyOmega 2.3.16
Mozilla/5.0 (X11; CrOS x86_64 7390.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.82 Safari/537.36

**Comment by FelisCatus** [comment]
In that case it is not possible for SwitchyOmega to change the proxy settings. Try changing the system proxy settings and see whether it works for you. Please contact your administrator in case it cannot be changed in any way.

**Comment by Tronic69** [comment]
I think you should recheck this, because FoxyProxy is able to manage it.

**Comment by FelisCatus** [comment]
I cannot confirm this on my side since I don't have a Chromebook.

I reviewed the code and checked the notice is only shown when `not_controllable` is returned by Chrome Extension API. Unless Chrome does something other than it claims, I'm pretty sure that the effective proxy settings cannot be changed even if an extension sets it successfully.

If you experience problems, please open `chrome://net-internals/#proxy` and copy the text there. Please do so once with all proxy setting extensions disabled and once again with FoxyProxy on. This would help to verify whether the proxy settings are indeed provided by policy.
