### ISSUE TITLE
Auto-switch setting for chrome extension? 

### ISSUE THREAD

**Issue by Aftersky** [FelisCatus/SwitchyOmega#688]
Hello,

Is there anyway I can setup SwitchyOmega to redirect traffic from chrome extensions through a proxy without defaulting to that proxy for all sites? 

The extensions tabs begin with "chrome-extension://" which is not a valid condition for autoswitch.

This is what I mean: https://dl.dropboxusercontent.com/u/73564551/lol/proxy.png

**Comment by FelisCatus** [comment]
You cannot "make" requests to `chrome-extension://` URIs -- these are loaded from file instead of sent over HTTP. Therefore it does not make sense to apply proxy rules for them.

If you are talking about requests made **BY extensions**, then I'm afraid SwitchyOmega does not support request by origins. Switch rules work by requests and their URL. It does not take pages, tabs or origins into consideration.
