### ISSUE TITLE
Diffrence between rule list format switchy and auto proxy and whats there use

### ISSUE THREAD

**Issue by anantatapase** [FelisCatus/SwitchyOmega#709]

**Comment by FelisCatus** [comment]
Rule lists are published rule sets from others. If you find any rule list published on the web useful, then you may integrate that into SwitchyOmega. Otherwise, it is perfectly fine not to use any rule lists.

The rule list you found probably labels itself as a Switchy rule list (those generated by SwitchyOmega and its predecessors) or an AutoProxy rule list (which comes from AutoProxy or AdBlock). It is fairly easy to tell which format it is -- just look at the first line of the rule list content and see whether it says `Switchy` or `AutoProxy`. And even better, SwitchyOmega will do this for you on the first time you paste or download the content.

Therefore, you don't need to care about the format that much. Most of the time, you can just focus on finding good rule lists and let SwitchyOmega do the rest for you.

**Comment by FelisCatus** [comment]
But if you may ask: what's the usage? Well, a rule list is... a list of rules, as you would expect. They work almost the same as Switch Profile rules, expect that they are automatically updated. Sometimes a set of rules are just too common so that they can be shared among multiple users and devices. As a result, a kind user may do you a favor and publish them on the web. For example, a list of internal websites that requires proxy connection can be particularly useful to co-workers at the same company. A set of rules that matches ads on pages can be used to block ads, provided you set an unreachable proxy for those ads that matches the rule list. URLs that get blocked by a firewall can also be crafted as a rule list so that you may route them through a proxy. The possibilities are endless. Unleash your imagination.

Wait, there's more! A rule list also enables you to edit the rules in your favorite text editor. They are based on plain text, so copying, pasting and replacing are easy and enjoyable. See that `[Edit source code]` button on Switch Profile? Click that, and... pow! You get a nicely formatted text representation for all your rules. These rules also have result attached to them, which is a distinct feature only available with `[SwitchyOmega Conditions]` format.

Well, I hope that should give you a brief of the rule lists feature. We wish you a pleasant journey exploring the features in SwitchyOmega. Follow us on [Github](https://github.com/FelisCatus/SwitchyOmega) to get updates and more pro-tips, only on SwitchyOmega Radio.
