### ISSUE TITLE
Support for NTLMv2

### ISSUE THREAD

**Issue by pfarikrispy** [FelisCatus/SwitchyOmega#735]
My proxies at work will require NTLMv2 support soon or I run the risk of locking my account each time when SwitchyOmega tries to route requests to a proxy.

I can't find a hint for support for this feature, so here is an official feature request.
By "support" I mean that SwitchyOmega will attempt authentication at the proxy the NTLM protocol and reusing the credentials from my already logged in Windows workstation.

As a user I want SwitchyOmega (SO) to authenticate me using NTLMv2 with proxies that require authentication by checking that option and have SO reuse my Windows credentials so that I can enjoy some single sign-on (SSO) functionality and don't need to reenter or store my user/pwd in SO

**Comment by FelisCatus** [comment]
Hi, thanks for the feature request. Unfortunately, SwitchyOmega is a configuration tool which does not implement any network protocol on its own.

NTLMv2 support should be part of Chromium Network Internals and [is tracked by Issue 22532 in the chromium project.](https://bugs.chromium.org/p/chromium/issues/detail?id=22532) I would suggest you go there and star the issue.

Also, according to [Chromium design documents on HTTP auth](https://www.chromium.org/developers/design-documents/http-authentication) (Remaining Work section):

> * Support NTLMv2 on Mac and Linux. Our portable NTLM code supports NTLMv1 only.

... which probably means that Chromium is already support NTLMv2 on Windows. If you are using Windows but you can't make NTLMv2 work for you, please open a new issue on the Chromium project. Otherwise, you'd have a better chance telling them the importance of NTLMv2 on your platform and persuade them to fix [Issue 22532](https://bugs.chromium.org/p/chromium/issues/detail?id=22532).

**Comment by pfarikrispy** [comment]
thanks man, will do
