### ISSUE TITLE
Feature Request: host keyword needed

### ISSUE THREAD

**Issue by GhostFlying** [FelisCatus/SwitchyOmega#742]
As the size limitation of sync, I want to minimize the rules. So I want to merge some different host of one site into one rule such as github.com, github.amazonaws.com. 

Now this can only be achieved by host regex as the url keyword does not work for HTTPS, but the performance of regex sounds not so good.

So if it possible to add host keyword or just make the url keyword works for HTTPS? 

Thanks.

**Comment by FelisCatus** [comment]
You can use host wildcard rules like `*github*`, which does match any host with `github` in it. It will compile to regex anyway, but don't worry about the performance that much because PAC run-time performance is not critical.

I would also like to add it is possible to work around sync limitations by creating several auto switch rules that "chain" together. For example:

* Auto Switch 1
  * (rules)
  * Default Profile: `Auto Switch 2`
* Auto Switch 2
  * (rules)
  * Default Profile: `Auto Switch 3`
* Auto Switch 3
  * (rules)
  * Default Profile: `Direct` or any profile you like

Select `Auto Switch 1` and all rules will be effectively run.
