### ISSUE TITLE
增加「纯文本编辑」功能

### ISSUE THREAD

**Issue by xinhugo** [FelisCatus/SwitchyOmega#80]
English title: Plain text-based editing for switch conditions

Proxy-SwitchySharp 里，「://*.twitter.com/」能匹配子域名，SwitchyOmega 不能，这是升级到新版的障碍。

类似这样的规则，我的代理规则列表有数百条，逐条编辑十分低效。

如果能有「纯文本编辑」功能（参考 Chrome 的 AdBlock Plus 扩展），则可以使用 Notepad++ 批量替换，改为旧版/新版都支持的正则表达式了。

如果有其他更高效的办法，希望不吝告知。感谢您的劳动，谢谢。

**Comment by xwj1003** [comment]
这个功能希望早点提供.只是对分隔符做个替换即可.应该不难.

**Comment by FelisCatus** [comment]
@xwj1003 我也希望早点提供啊，但我自己必须去花精力去开发啊……我倒是也想自己不用太花精力，有志愿者帮忙写好然后 pull request ，我只要负责 merge 就可以了，多好。但这个项目并没有那么多关注吧……并没有太多人愿意贡献代码。

**Comment by FelisCatus** [comment]
暂定的纯文本编辑格式： https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format#result-profile

格式是从规则列表的基础上演变而来，有考虑过文本编辑器的替换等功能。如果有什么建议请提出。

**Comment by xinhugo** [comment]
没有建议喔。

**Comment by xwj1003** [comment]
*.example.com

; This is a UrlWildcardCondition.
:UrlWildcardCondition https://*.google.com/*

; This is a UrlRegexCondition. Most types of conditions can be represented with :ConditionType pattern
:UrlRegexCondition ^https://www\.example\.(net|org)/

; Conditions can be prefixed with ! to make it exclusive. Any requests matching an exclusive condition will
; use the "default profile" instead of "match profile".
!*.internal.example.org
----
UrlWildcardCondition 
UrlRegexCondition 
太长了,建议改成缩写. uw: urlwild,ur: urlregex, dw:domainwild, dr:domainregex...

**Comment by FelisCatus** [comment]
@xwj1003 嗯，等我弄一个缩写列表出来……

**Comment by FelisCatus** [comment]
@xwj1003 缩写就是[这些了](https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format#abbreviations)，大部分缩写都考虑了，包括首字母缩写和其他的东西。

**Comment by FelisCatus** [comment]
v2.3.2 添加了 [Omega 样式的规则列表](https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format)。同时，自动切换模式增加了基于此规则列表的“编辑源代码”功能，开启后右侧显示的问号按钮可以打开格式说明。关闭源代码视图时或者保存时，会自动提示代码中存在的错误，且错误信息已经翻译。（保持编辑源代码功能开启后，下次再次打开同一情景模式，会直接进入源代码编辑界面，免除了加载规则编辑用户界面的开销，适合规则太多以至于感觉卡顿的用户。）

新的规则列表虽然[已经经过不少测试了](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-pac/test/rule_list.coffee)，并且处理了很多边界条件和特殊情况，但仍然有可能会出现这样或者那样的考虑不周。如果遇到任何问题请及时反馈。

----

题外话：这次的功能虽说不是主要功能，且看上去改动不大，但其实这是一个相当漫长的过程。从规则列表格式制定，到具体的代码实现和测试，花费了太多太多的精力。具体付出了多少，即使只看表面的代码量也能清楚。总之还是非常感谢大家能够耐心陪伴我走过这段的时间，谢谢大家的支持和建议。
接下来[2.4 版本的预定目标](https://github.com/FelisCatus/SwitchyOmega/milestones/2.4)中，大部分都属于这样的情况，看似改动不大但需要投入很多精力。但是我仍然会尽力去把这些事情做到最好。因为我仍然在追求完美，追求技术上和产品上的合理，不希望留下这样那样的遗憾。
以后希望大家还能继续支持此项目，以及保持足够的耐心。

**Comment by xinhugo** [comment]
好的，谢谢你的持续开发。

**Comment by FelisCatus** [comment]
@xinhugo 快去试试看吧，等着你的反馈呢～

**Comment by xinhugo** [comment]
手工更新到最小版本，看到「编辑源代码」功能了。
