### ISSUE TITLE
Full URLs for HTTPS are no longer provided to PAC scripts. Affects Url* rules.

### ISSUE THREAD

**Issue by swissmountainleader** [FelisCatus/SwitchyOmega#845]
On both OSX and chromebook, expressions like 

https://www.xyz.com/sub/*

(note HTTPS) have stopped working. They also no longer appear to work in externally hosted PAC files but the same PAC files work with Firefox.

This appears to be a change in the way Chrome is evaluating these expressions.

Host wildcards are working just fine.

**Comment by FelisCatus** [comment]
Did you report this to the Chromium project?

Also, could you try adding `alert(url);` in your PAC scripts? This should print the URLs you are visiting to `chrome://net-internals/#events`. In this way you can check whether the full URL is provided to the script or not.

Example PAC script:

```js
function FindProxyForURL(url, host) {
        alert(url);
        return "DIRECT";
}
```

**Comment by FelisCatus** [comment]
Ah, fine. This seems to be an intentional breaking change according to the following issue on Chromium.

https://bugs.chromium.org/p/chromium/issues/detail?id=619097

I have no idea why they keep the original issue that introduces this change private though.

**Comment by FelisCatus** [comment]
Code review for the exact patch: https://codereview.chromium.org/1996773002

**Comment by FelisCatus** [comment]
We probably want to add a notice for `UrlWildcard` conditions in SwitchyOmega to show they won't work as intended and the reason behind this.

**Comment by swissmountainleader** [comment]
OK, I had assumed it was a chrome change and looked at the change log but missed that for some reason.

That's a shame, a powerful part of proxy handling is gone.

**Comment by FelisCatus** [comment]
I'm re-opening this issue to track the progress of adding the notice to SwitchyOmega. Feel free to unsubscribe if you are no longer interested in this.

**Comment by DailyShana** [comment]
>Stripping of https:// URLs can (temporarily) be switched off using either
  The policy PacHttpsUrlStrippingEnabled (set it to False)
or
  The command line flag --unsafe-pac-url

**Comment by Bluep** [comment]
I really start to hate Chrom(e|ium) ... 3rd change in less than half a year that annoys me really bad.
If it wouldn't be for real security issues, I'd stay with M50.. :(

But anyways, big THANKS for your work on SwitchyOmega, @FelisCatus

**Comment by Bluep** [comment]
I really start to hate Chrom(e|ium) ... 3rd change in less than half a year that annoys me really bad.
If it wouldn't be for real security issues, I'd stay with M50.. :(

But anyways, big THANKS for your work on SwitchyOmega, @FelisCatus 

/edit: Yes @ 
> We probably want to add a notice for UrlWildcard conditions in SwitchyOmega

**Comment by FelisCatus** [comment]
As far as I know there is a security issue but that more or less requires the attacker to control what PAC script you run. The most harmful result could be the full URLs that you are visiting are leaked to the attacker. Please note that those URLs are supposed to be secret exclusively known between you and the website because, well, it is HTTPS. Updating to Chrome 51 will fix that.

However, if your PAC script is a local file (or a embedded script) written entirely by yourself then you are probably not vulnerable to this particular issue. In the case of SwitchyOmega, if you write all the switch rules yourself AND you do not rely on PAC Profiles then I think you are pretty safe. But, if you rely on WPAD or other resources over the internet (say, a PAC Profile with a remote URL like `http://wpad/wpad.dat` or `http://yourcompany.example.com/foobar.pac`), then you should be aware that the issue above and that certainly may affect you. If you are not 100% sure, PLEASE INSTALL THE UPDATE ASAP.

You never know what the website developers will put in the URLs. Yes, under extreme circumstances, nothing could stop those people from transmitting your password in clear text in URL params, and it is not their fault because they assume HTTPS will protect that. But that particular issue with PAC script will leak the URL before HTTPS conversations are even started, and that's why it is a big deal.

Please note that the above information is only provided for your reference. I do not guarantee anything, nor am I suggesting that you should not update. **Bottom line: You should update unless you are technical and you are willing to take the risk.**

**Comment by Bluep** [comment]
> PLEASE INSTALL THE UPDATE ASAP
If that was directed at me - yeah, I'm already running the latest chrome again... that's why I noticed the change. I'm using SwitchyOmega to parse some traffic with a local mitm proxy, and that stopped working because of this chrome change. Using the policy / cmd line flag is a fast workaround for now, but as soon as that support is going to be dropped, I have a 'tiny' problem - tunneling the whole domain's traffic through the proxy works, but is awfully slow (of course..) compared to redirecting only the url to the proxy.

**Comment by achekulaev** [comment]
I guess URL Wildcard and URL Regexp should be renamed to Host Wildcard and Host Regexp respectfully to mirror their effective functionality.

**Comment by Bluep** [comment]
@achekulaev : No, as for non-HTTPS it works as intended - I'd suggest adding a " (HTTP only) to both of them.

**Comment by FelisCatus** [comment]
I'm not pointing at anybody... Just to want to give some tl;dr to random people who came here following a Google search or other links.

Yes, as @Bluep said. The whole point of this issue is to document the new changes. Also, we already have `HostWildcard` and `HostRegex` rules under "Advanced Switch Conditions". Any other suggestions?

**Comment by FelisCatus** [comment]
I need to prioritize this since people keep getting confused... Also, in some cases the SwitchyOmega extension icon does not agree with the actual result, which is even worse.

(Well, this is because SwitchyOmega cannot read the final decision and had to use some internal matching algorithm to change the icon. That internal matching algorithm, of course, is not subject to the change.)

If we must do this 100% right, then I would go with @Bluep and add `(HTTP Only)` to both the interface text and the underlying logic. That would disable the whole thing even if the user is using older Chrome versions or has changed flags though.

Maybe we need to detect Chrome versions... Well, that's awkward. I don't think it is possible to do that in PAC scripts.

**Comment by mashaalmemon** [comment]
Just realized that PAC was behaving differently and found this thread. While I understand the reasons behind it makes proxy autoconfiguration that much less intelligent. The '--unsafe-pac-url' should be kept in place for those who are willing to take the risk I think and deal with the consequences.

**Comment by FelisCatus** [comment]
v2.3.22 introduces a warning message for the limitation. We've also got [a wiki page](https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-Full-URL-Limitation) documenting the details.

**Comment by zypA13510** [comment]
Hi, could you please add [this information](https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-Full-URL-Limitation) to [these](https://github.com/FelisCatus/SwitchyOmega/wiki/URL-regex-condition) [two](https://github.com/FelisCatus/SwitchyOmega/wiki/URL-wildcard-condition) wiki pages? Also, the exclamation sign (when selecting URL regex condition) should probably link to this page on click (if that is possible). It took me half an hour to figure out that it doesn't work in HTTPS. I saw the sign, but it doesn't say what exactly should I be careful about.

**Comment by FelisCatus** [comment]
@zypA13510 Wiki page updated. I will improve the sign soon.
