### ISSUE TITLE
Autoswitch for listed domains (or URLs)

### ISSUE THREAD

**Issue by leledumbo** [FelisCatus/SwitchyOmega#873]
I really need this as my ISP currently renders certain websites incomplete due to their ads injection. The current volatile switch is not enough, since once the browsing session ends, so is the autoswitch. Gotta PayPal? I'd like to buy you some beers (or coke or coffee or tea, whatever you prefer :3).

**Comment by FelisCatus** [comment]
Are you trying to add permanent rules to the Auto Switch? You can do that by using the "Add Condition" menu item in the dropdown. You can only see this item when a Switch Profile is activated.

Please note that the menu entry with the domain name and the filter icon is dedicated for temporary rules. I apologize if this causes confusions, and I plan to clarify this a little bit. This issue is tracked at #515. English comments are more than welcome there and you can ignore the Chinese there if you don't understand them.

SwitchyOmega is not accepting donation at the moment. This is also tracked in #131. I would be happy to solve your problems and consistently improvement the project without any drinks. Thanks though :)

**Comment by leledumbo** [comment]
Found it. Yes, it seems easily unnoticeable before you tell me. Works fine now so it can be closed :)
