### ISSUE TITLE
SwitchyOmega seems not to work with shadowsocks-windows after chrome updated to 53

### ISSUE THREAD

**Issue by BerwinVon** [FelisCatus/SwitchyOmega#885]
I don't know if anyone else has the same problem.
It worked fine before chrome updated to 53, and I didn't change any settings. ss has no problem becanuse I can use proxy when I check the Global Proxy. I check the log of ss and it seems like ss don't receive the request of SwitchOmega. Need help, please.

version:
shadowsocks-windows 3.0.0.0
SwitchyOmega 2.3.19

**Comment by rebiu** [comment]
try shadowsocks-windows latest release
https://github.com/shadowsocks/shadowsocks-windows/releases

or try shadowsocks-windows beta version
https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i

because here I fine
beta shadowsocks-windows 1.0.80
SwitchyOmega 2.3.19
Chrome 53.0.2785.116
Win 10 x64 14393
Win 10 x64

or check your PC :)

**Comment by BerwinVon** [comment]
Hi, rebiu. I have tried what you suggest but still not work. Thanks anyway.

**Comment by FelisCatus** [comment]
Is this something like #557?

**Comment by celeron533** [comment]
All good from my environment

SS 3.3.4
Win10 build 14393
Chrome 53.0.2785.143
Using socks NOT http proxy

![image](https://cloud.githubusercontent.com/assets/3608762/19624015/071fca54-9916-11e6-83ef-840d4b6413dc.png)

**Comment by BerwinVon** [comment]
Ah...
I have done nothing (including updating) but it worked again a fews days ago. I still can't figure out why.

**Comment by FelisCatus** [comment]
Closing this for now. Please refer to #557 in case you have more problems.
