### ISSUE TITLE
Pac Script retrieved from the browser cache

### ISSUE THREAD

**Issue by ldumaine** [FelisCatus/SwitchyOmega#886]
Hi,

Regarding PAC profiles, when I click on "download profile now"  I expect the extension to download the latest version of the pac file directly from the server. Instead of this I get the copy from the browser cache. The work around being to empty chrome's cache.

N.B.: We use an URL like http://proxypac.domain.lan with with no path and especially no ".pac" extention, however the content-type is correct (application/x-ns-proxy-autoconfig)..

Regards, Luc.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by celeron533** [comment]
Please try to add a dummy parameter in the URL to force refresh the cache:
`http://proxypac.domain.lan/?id=0`

**Comment by ldumaine** [comment]
It worked, thank you.

I since changed the configuration of the http server serving the proxy.pac file, in order to make in uncacheable, now if i click in "download profile now" I always get the latest file directly from the server.

Anyway the button being called "download profile now", I would expect this action to bypass the browser cache... I don't know if it's technically feasible..

**Comment by FelisCatus** [comment]
SwitchyOmega can't change the caching policy for Chrome. Sorry for that.

I did write a [cache buster in source code](
https://github.com/FelisCatus/SwitchyOmega/blob/497d5de8ce5a4e8f1aea68c8ccffd9ba1c304d8e/omega-target-chromium-extension/src/options.coffee#L19), but it uses the same dummy parameter mechanism behind the scene.

Currently, it is unused when you click on download profile now, mainly because it changes the URL the user provide in a not-so-obvious way and could cause issues depending on remote behavior.

Shall we enable that? Or could we probably try with the parameter first, and fallback to the original URL when the request fails?

**Comment by FelisCatus** [comment]
I made that button hit the server with the dummy parameter first, and fallback if the update is unsuccessful.

A release containing the new feature is coming soon.

**Comment by FelisCatus** [comment]
v2.3.20 is released with the feature implemented. It also shows better error messages.
