### ISSUE TITLE
My SwtichyOmega extension (V2.3.21) in Chrome (V47.0.2526.106) is always disabled while restarting the Chrome.

### ISSUE THREAD

**Issue by KimXiao** [FelisCatus/SwitchyOmega#932]
My SwtichyOmega extension (V2.3.21) in Chrome (V47.0.2526.106) is always disabled while restarting the Chrome (exit the chrome application then launch it next time). I should re-enable it from the Chrome->Extension page every time I start to use it. Do I miss any setting in the configuration of SwitchyOmega?

**Comment by FelisCatus** [comment]
Hmm... This is weird. Where did you get it from? If you downloaded from Github, try installing from Chrome Web Store instead because Chrome could disable extensions not from the store from time to time.

If not, try disabling other extensions, especially those with permissions to manage extensions.

I'm closing this anyway because SwitchyOmega will not disable itself. Also it cannot re-enable itself when it is disabled because no code could run. There is no setting or configuration for this.

**Comment by KimXiao** [comment]
Sorry for late...
Yeah, I guess I downloaded it from Github, I will try to reinstall it from store, and let you know the result later. Thanks a lot.

**Comment by KimXiao** [comment]
I am sorry that I still get the same issue after reinstall it via chrome store. Any suggestions? Thanks.

**Comment by FelisCatus** [comment]
Then you probably need to look for other extensions who have the permission to control extensions. I would suggest disabling all extensions except SwitchyOmega and see if the same thing still happens.
