### ISSUE TITLE
Popup not appearing issue

### ISSUE THREAD

**Issue by satgitrepo** [FelisCatus/SwitchyOmega#941]
Sometimes the popup to change the proxy never appears even after trying 10 times.

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by FelisCatus** [comment]
Did you enable Quick Switch in options? If enabled, then clicking on the extension icon will cycle through those proxies instead of showing a popup.

If not, could you please take some screenshots when the popup window does not show up? You can also RIGHT-click on the extension icon and select "Save error log" there (AFTER you reproduce the problem) and then upload it here. That would be very helpful.

**Comment by FelisCatus** [comment]
Closing for now. Please re-open if you have more information.
