### ISSUE TITLE
Update angular.js to 1.5.9+ (it's already 2.x on official site)

### ISSUE THREAD

**Issue by lainverse** [FelisCatus/SwitchyOmega#986]
Hi,

Mozilla implemented ability to install Google Chrome extensions in their browser (Firefox). However, to do so permanently extension have to pass validation on Mozilla's side and due to usage of angular.js < 1.5.9 it doesn't. https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md

Could you please consider update of that library to 1.5.9 or higher?

It won't work on Fx yet, though.

**Comment by FelisCatus** [comment]
I don't even know whether it would work under Angular 1.5.9 but I can take some time to upgrade the dependencies later. I wouldn't even try Angular 2 though because it would be a breaking change.

Firefox porting is tracked at #980 but as far as I know it won't work since Firefox does not have `chrome.proxy` implemented.

**Comment by FelisCatus** [comment]
Angular is updated to 1.5.9 in #1030. Please see there and check the Firefox porting in progress.
